In [145]:
import torch
import math 
import torch.nn.functional as F

batch = {
    'targets': torch.randn(2, 8, 64),
    'context_vectors': torch.randn(2, 8, 64),
    'mask': torch.tensor([[True, True, False, False, False, True, False, True], [True, True, False, False, False, True, False, True]]),
}

In [156]:


calc_loss_proper(batch, 1, 9)
    
    
    

sim_targets.shape torch.Size([2, 4, 10, 64])
sims.shape torch.Size([2, 4, 10])
sims.shape torch.Size([2, 10, 4])
tensor([[[ 0.1281,  0.0933,  0.0367,  0.0962],
         [-0.0189, -0.1945, -0.1550,  0.1376],
         [-0.0189, -0.1945,  0.1209,  0.1142],
         [-0.1352, -0.1945, -0.1550,  0.1142],
         [-0.0189, -0.1945, -0.1550, -0.0005],
         [ 0.0146, -0.1945,  0.1209, -0.0005],
         [-0.1352,  0.1060, -0.1550,  0.1142],
         [-0.1352,  0.1060, -0.1386,  0.1376],
         [-0.1352, -0.0711, -0.1386, -0.0005],
         [ 0.0146,  0.1060, -0.1550,  0.1376]],

        [[ 0.1714, -0.0463,  0.1032, -0.0398],
         [ 0.0543,  0.0474, -0.2090, -0.1568],
         [ 0.0316, -0.0538, -0.2090, -0.0862],
         [ 0.0316, -0.0538, -0.1191, -0.1568],
         [ 0.0543, -0.0356, -0.2090,  0.2554],
         [ 0.0543, -0.0356,  0.2331, -0.1568],
         [ 0.0316, -0.0356,  0.2331, -0.1568],
         [ 0.0316,  0.0474, -0.2090, -0.1568],
         [ 0.0316, -0.0356,  0.2331, -0

tensor(2.2222)

In [ ]:
batch_size, num_tokens, emb_size = batch['targets'].shape

torch.count_nonzero(x, dim=0)


In [5]:
d= torch.tensor([
    [1, 2, 1, 0, 1, 0],
    [1, 0, 0, 0, 1, 2],
])

In [18]:
nz = torch.count_nonzero(d > 0, dim=1)
nz



tensor([4, 3])

In [47]:
def make_pretrain_mask(batch_size, num_chunks, mask_prob, mask_length):
    mask = 1 * (torch.rand(batch_size, num_chunks) < mask_prob)
        
    mask[:, mask_length:] = mask[:, mask_length:] - mask[:, : -mask_length]
    mask = mask.cumsum(1) > 0
    
    non_zero = torch.count_nonzero(mask, dim=1)
    set_extra_ones = non_zero.max() - non_zero
    
    for i in range(batch_size):
        j = 0
        while set_extra_ones[i] > 0:
            if not mask[i, j]:
                mask[i, j] = True
                set_extra_ones[i] -= 1
            j += 1
    
    return mask


tensor([85, 85, 85, 85, 85, 85, 85, 85, 85, 85])

In [15]:
for i in range()

tensor([[0, 0],
        [0, 1],
        [0, 2],
        [0, 4],
        [1, 0],
        [1, 4],
        [1, 5]])

In [48]:
context_vectors = torch.rand(8, 16, 128)
features = torch.rand(8, 16, 128)

mask = make_pretrain_mask(8, 16, 0.3, 2)



In [50]:
mask.sum(1)

tensor([11, 11, 11, 11, 11, 11, 11, 11])

In [55]:
mask[0]

tensor([ True,  True,  True,  True,  True,  True,  True,  True, False, False,
        False, False,  True,  True, False,  True])

In [57]:
context_vectors[0, 0, :]

tensor([2.4521e-01, 1.5442e-01, 1.3543e-01, 4.0935e-01, 2.9178e-01, 7.0763e-01,
        6.3046e-01, 7.8960e-02, 1.7042e-01, 8.6654e-01, 5.2912e-01, 8.5400e-01,
        9.7545e-02, 5.2555e-01, 8.8126e-01, 8.4989e-01, 9.7351e-01, 2.8159e-01,
        7.0202e-01, 4.1599e-01, 7.1815e-01, 8.4082e-01, 4.0098e-01, 4.3547e-01,
        9.3482e-01, 8.0287e-01, 1.2611e-01, 2.7833e-01, 9.8822e-01, 1.9635e-01,
        3.0488e-02, 5.1590e-01, 4.2680e-01, 3.1658e-01, 3.9386e-01, 4.8499e-01,
        7.8971e-02, 4.0638e-01, 8.4209e-01, 4.5078e-01, 6.0780e-01, 3.5798e-01,
        8.9602e-01, 3.2764e-01, 9.6160e-01, 3.6570e-01, 5.1641e-01, 5.2647e-01,
        1.7558e-01, 6.9024e-02, 8.7559e-01, 2.6599e-01, 3.6647e-01, 8.1979e-01,
        5.3891e-01, 6.8915e-01, 1.5978e-01, 9.9805e-01, 2.8983e-01, 6.1333e-01,
        2.1150e-01, 8.0969e-01, 8.4807e-01, 4.7146e-01, 9.1682e-01, 6.1308e-02,
        3.7447e-01, 5.2176e-02, 4.1289e-01, 5.1539e-01, 5.5136e-01, 9.1067e-01,
        1.1590e-01, 7.6090e-01, 9.6427e-

In [135]:
masked_context = context_vectors[mask].view(context_vectors.size(0), -1, context_vectors.size(-1))
masked_features = features[mask].view(features.size(0), -1, features.size(-1))



In [ ]:
pick_negatives()

In [70]:
torch.tensor([[1, 2], [1, 2], [1, 2]]).flatten()

tensor([1, 2, 1, 2, 1, 2])

In [71]:
torch.arange(5).unsqueeze(-1).expand(-1, 3)

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4]])

In [69]:
torch.arange(5).unsqueeze(-1).expand(-1, 3).flatten()

tensor([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
l = torch.rand(8, 11, 4, 64)


In [134]:
def pick_negatives(x, num_negatives):
    # for each el in seq_len get num_negatives other els from the same batch
    batch_size, seq_len, emb_size = x.shape 
    
    self_indexes = torch.arange(seq_len).unsqueeze(-1).expand(-1, num_negatives) # (seq_len, num_negatives)

    neg_idxs = torch.randint(low=0, high=seq_len - 1, size=(batch_size, seq_len, num_negatives))
                             
    neg_idxs[neg_idxs >= self_indexes.unsqueeze(0)] += 1
    neg_idxs = neg_idxs.view(batch_size, seq_len * num_negatives, 1).expand(batch_size, seq_len * num_negatives, emb_size)

    res = torch.gather(x, 1, neg_idxs).view(batch_size, seq_len, num_negatives, emb_size)
    return res

    
l = torch.arange(20).view(2, 10, 1).expand(2, 10, 8)
r = pick_negatives(l, 5)
r[1]
    

tensor([[[14, 14, 14, 14, 14, 14, 14, 14],
         [13, 13, 13, 13, 13, 13, 13, 13],
         [14, 14, 14, 14, 14, 14, 14, 14],
         [15, 15, 15, 15, 15, 15, 15, 15],
         [13, 13, 13, 13, 13, 13, 13, 13]],

        [[14, 14, 14, 14, 14, 14, 14, 14],
         [17, 17, 17, 17, 17, 17, 17, 17],
         [18, 18, 18, 18, 18, 18, 18, 18],
         [16, 16, 16, 16, 16, 16, 16, 16],
         [10, 10, 10, 10, 10, 10, 10, 10]],

        [[11, 11, 11, 11, 11, 11, 11, 11],
         [11, 11, 11, 11, 11, 11, 11, 11],
         [15, 15, 15, 15, 15, 15, 15, 15],
         [14, 14, 14, 14, 14, 14, 14, 14],
         [16, 16, 16, 16, 16, 16, 16, 16]],

        [[12, 12, 12, 12, 12, 12, 12, 12],
         [11, 11, 11, 11, 11, 11, 11, 11],
         [14, 14, 14, 14, 14, 14, 14, 14],
         [11, 11, 11, 11, 11, 11, 11, 11],
         [12, 12, 12, 12, 12, 12, 12, 12]],

        [[13, 13, 13, 13, 13, 13, 13, 13],
         [11, 11, 11, 11, 11, 11, 11, 11],
         [13, 13, 13, 13, 13, 13, 13, 13],
   

In [130]:
i

torch.Size([2, 50, 8])

In [129]:
r[0, 5, :, :]

tensor([[3, 3, 3, 3, 3, 3, 3, 3],
        [8, 8, 8, 8, 8, 8, 8, 8],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4]])

In [118]:
[1, 3, :]

tensor([13, 13, 13, 13, 13, 13, 13, 13])

In [100]:
torch.gather(torch.arange(10).view(2, 5), 1, torch.tensor([[0, 1], [0, 1]]))

tensor([[0, 1],
        [5, 6]])

In [ ]:
8, 11, 128 <- context
8, 

In [67]:
masked_context.shape

torch.Size([8, 11, 128])

In [66]:
F.cosine_similarity(masked_context, masked_features, 2).shape

torch.Size([8, 11])

In [ ]:
batch_size, num_tokens, emb_size = batch['targets'].shape
targets, preds = batch['targets'], batch['context_vectors']
norm_targets = torch.norm(targets, 2, dim=2, keepdim=True) # batch_size, num_tokens, 1
norm_preds = torch.norm(preds, 2, dim=2, keepdim=True) # batch_size, num_tokens, 1

good_targets = targets / norm_targets
good_preds = preds / norm_preds

# targets = torch.cat([targets, 100 * torch.ones(batch_size, 5, emb_size, device=batch['targets'].device)], dim=1)

sim = good_preds @ good_targets.permute(0, 2, 1) # batch_size, num_tokens, num_tokens
sim = sim[batch['mask']] # num_masked, num_tokens -- for every masked prediction, logits  per all seq
labels = torch.tile(torch.arange(num_tokens), (batch_size, 1))
labels = labels[batch['mask']].to(batch['targets'].device)
sim = sim * math.exp(log_temp)
unreduced_loss = F.cross_entropy(sim, labels, reduction='none')

# set batch=1, num_chunks=8 to see how things works
print(sim[:batch['mask'][0].sum()])
print(batch['mask'][0])
print(labels[:batch['mask'][0].sum()])
print(F.cross_entropy(sim, labels, reduction='none'))
# example of good vals
# tensor([[ 2.7511, -0.5308, -0.3625, -0.2960, -0.2756, -0.3741, -0.3812, -0.5015],
#     [-0.6111,  2.7569, -0.2216, -0.6170, -0.3746, -0.5203, -0.1013, -0.3689],
#     [-0.1247, -0.1079, -0.2098, -0.2186,  2.7137, -0.1079, -0.1882, -0.3002],
#     [-0.0668, -0.6090, -0.4044, -0.5796, -0.3214,  2.5963, -0.1835, -0.6229],
#     [-0.3907, -0.5906, -0.5988, -0.4737, -0.7476, -0.6327,  2.7852, -0.6409],
#     [-0.3811, -0.4140, -0.5004, -0.3402, -0.3983, -0.5376, -0.3075,  2.6888]],
#    device='cuda:0', grad_fn=<MulBackward0>)
# tensor([[ True,  True, False, False,  True,  True,  True,  True]])
# tensor([0, 1, 4, 5, 6, 7], device='cuda:0')
# loss: 0.27600 -- close to orthogonal optimum

batch['per_masktoken_loss'] = unreduced_loss
batch['loss'] = unreduced_loss.mean()