In [2]:
import pandas as pd

df = pd.read_csv('/Users/ksc/Downloads/data 3/band/‹¥è /03_27_2024_15_33_events.csv')
df


Theme  Wait_start_time  Song_start_time  Song_end_time  Valence
0    classical 67     1.711543e+09     1.711543e+09   1.711543e+09      3.0
1          rock 4     1.711543e+09     1.711543e+09   1.711543e+09      4.0
2    classical 62     1.711543e+09     1.711543e+09   1.711543e+09      3.0
3    classical 18     1.711543e+09     1.711543e+09   1.711543e+09      4.0
4   classical 100     1.711543e+09     1.711543e+09   1.711543e+09      2.0
5          pop 13     1.711543e+09     1.711543e+09   1.711543e+09      2.0
6          pop 90     1.711543e+09     1.711543e+09   1.711543e+09      3.0
7          pop 47     1.711543e+09     1.711543e+09   1.711543e+09      4.0
8          pop 56     1.711543e+09     1.711543e+09   1.711543e+09      4.0
9         rock 14     1.711543e+09     1.711543e+09   1.711543e+09      4.0
10   classical 69     1.711543e+09     1.711543e+09   1.711543e+09      3.0
11        rock 22     1.711543e+09     1.711543e+09   1.711543e+09      4.0
12         pop 41     1.711543e+09     1.711543e+09   1.711543e+09      4.0
13         pop 58     1.711543e+09     1.711543e+09   1.711543e+09      4.0
14        rock 84     1.711543e+09     1.711543e+09   1.711543e+09      2.0
15  electronic 14     1.711543e+09     1.711543e+09   1.711544e+09      3.0
16  electronic 69     1.711544e+09     1.711544e+09   1.711544e+09      4.0
17         pop 53     1.711544e+09     1.711544e+09   1.711544e+09      3.0
18   classical 35     1.711544e+09     1.711544e+09   1.711544e+09      4.0
19        rock 50     1.711544e+09     1.711544e+09   1.711544e+09      3.0
20        rock 15     1.711544e+09     1.711544e+09   1.711544e+09      4.0
21   classical 31     1.711544e+09     1.711544e+09   1.711544e+09      3.0
22   classical 14     1.711544e+09     1.711544e+09   1.711544e+09      3.0
23         pop 65     1.711544e+09     1.711544e+09   1.711544e+09      2.0
24        rock 35     1.711544e+09     1.711544e+09   1.711544e+09      4.0
25   electronic 3     1.711544e+09     1.711544e+09   1.711544e+09      3.0
26         pop 39     1.711544e+09     1.711544e+09   1.711544e+09      2.0
27   classical 61     1.711544e+09     1.711544e+09   1.711544e+09      3.0
28  electronic 35     1.711544e+09     1.711544e+09   1.711544e+09      3.0
29        rock 31     1.711544e+09     1.711544e+09   1.711544e+09      4.0
30         pop 14     1.711544e+09     1.711544e+09   1.711544e+09      3.0
31  electronic 46     1.711544e+09     1.711544e+09   1.711544e+09      3.0
32        rock 92     1.711544e+09     1.711544e+09   1.711544e+09      4.0
33  electronic 51     1.711544e+09     1.711544e+09   1.711544e+09      4.0
34  electronic 13     1.711544e+09     1.711544e+09   1.711544e+09      3.0
35   classical 27     1.711544e+09     1.711544e+09   1.711544e+09      3.0
36        rock 89     1.711544e+09     1.711544e+09   1.711544e+09      4.0
37    classical 9     1.711544e+09     1.711544e+09   1.711544e+09      3.0
38   classical 38     1.711544e+09     1.711544e+09   1.711544e+09      2.0
39        rock 57     1.711544e+09     1.711544e+09   1.711544e+09      4.0
40  electronic 79     1.711544e+09     1.711544e+09   1.711544e+09      3.0
41   electronic 6     1.711544e+09     1.711544e+09   1.711544e+09      2.0
42   classical 25     1.711544e+09     1.711544e+09   1.711544e+09      2.0
43        rock 24     1.711544e+09     1.711544e+09   1.711544e+09      4.0
44  electronic 52     1.711544e+09     1.711544e+09   1.711544e+09      3.0
45  electronic 68     1.711544e+09     1.711544e+09   1.711544e+09      2.0
46  electronic 41     1.711544e+09     1.711544e+09   1.711544e+09      2.0
47  electronic 87     1.711544e+09     1.711544e+09   1.711544e+09      3.0
48        rock 34     1.711544e+09     1.711544e+09   1.711544e+09      4.0
49         pop 96     1.711544e+09     1.711544e+09   1.711544e+09      3.0
50         pop 85     1.711544e+09     1.711544e+09   1.711545e+09      3.0
51          pop 7     1.711545e+09     1.711545e+09   1.7115

In [6]:
1 / 250

0.004

In [ ]:
1 -> 1/250

In [13]:
start = 1711542997.2122576
df['start_delta'] = df['Song_start_time'] - start
df['end_delta'] = df['Song_end_time'] - start
df['start_index'] = (df['start_delta'] // 0.004).astype(int)
df['end_index'] = (df['end_delta'] // 0.004).astype(int)
df

Theme  Wait_start_time  Song_start_time  Song_end_time  Valence  \
0    classical 67     1.711543e+09     1.711543e+09   1.711543e+09      3.0   
1          rock 4     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
2    classical 62     1.711543e+09     1.711543e+09   1.711543e+09      3.0   
3    classical 18     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
4   classical 100     1.711543e+09     1.711543e+09   1.711543e+09      2.0   
5          pop 13     1.711543e+09     1.711543e+09   1.711543e+09      2.0   
6          pop 90     1.711543e+09     1.711543e+09   1.711543e+09      3.0   
7          pop 47     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
8          pop 56     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
9         rock 14     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
10   classical 69     1.711543e+09     1.711543e+09   1.711543e+09      3.0   
11        rock 22     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
12         pop 41     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
13         pop 58     1.711543e+09     1.711543e+09   1.711543e+09      4.0   
14        rock 84     1.711543e+09     1.711543e+09   1.711543e+09      2.0   
15  electronic 14     1.711543e+09     1.711543e+09   1.711544e+09      3.0   
16  electronic 69     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
17         pop 53     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
18   classical 35     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
19        rock 50     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
20        rock 15     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
21   classical 31     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
22   classical 14     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
23         pop 65     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
24        rock 35     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
25   electronic 3     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
26         pop 39     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
27   classical 61     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
28  electronic 35     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
29        rock 31     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
30         pop 14     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
31  electronic 46     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
32        rock 92     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
33  electronic 51     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
34  electronic 13     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
35   classical 27     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
36        rock 89     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
37    classical 9     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
38   classical 38     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
39        rock 57     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
40  electronic 79     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
41   electronic 6     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
42   classical 25     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
43        rock 24     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
44  electronic 52     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
45  electronic 68     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
46  electronic 41     1.711544e+09     1.711544e+09   1.711544e+09      2.0   
47  electronic 87     1.711544e+09     1.711544e+09   1.711544e+09      3.0   
48        rock 34     1.711544e+09     1.711544e+09   1.711544e+09      4.0   
49         pop 96     1.711544e+09     1.711544e+09   1.711544

In [21]:
song_to_id = {song: ind for ind, song in enumerate(sorted(df['Theme']))}
print(len(song_to_id))

52


In [25]:
import torch 

song_ids = torch.ones(390_000, dtype=int) * -1
is_liked = torch.ones(390_000, dtype=int) * -1
for _, row in df.iterrows():
    start_ind = row['start_index']
    end_ind = row['end_index']
    song_ids[start_ind : end_ind] = song_to_id[row['Theme']]
    is_liked[start_ind : end_ind] = 1 if row['Valence'] >= 3 else 0

tensor(0.8823)
tensor(0.8823)


In [26]:
song_to_id

{'classical 100': 0,
 'classical 14': 1,
 'classical 18': 2,
 'classical 25': 3,
 'classical 27': 4,
 'classical 31': 5,
 'classical 35': 6,
 'classical 38': 7,
 'classical 61': 8,
 'classical 62': 9,
 'classical 67': 10,
 'classical 69': 11,
 'classical 9': 12,
 'electronic 13': 13,
 'electronic 14': 14,
 'electronic 3': 15,
 'electronic 35': 16,
 'electronic 41': 17,
 'electronic 46': 18,
 'electronic 51': 19,
 'electronic 52': 20,
 'electronic 6': 21,
 'electronic 68': 22,
 'electronic 69': 23,
 'electronic 79': 24,
 'electronic 87': 25,
 'pop 13': 26,
 'pop 14': 27,
 'pop 39': 28,
 'pop 41': 29,
 'pop 47': 30,
 'pop 53': 31,
 'pop 56': 32,
 'pop 58': 33,
 'pop 65': 34,
 'pop 7': 35,
 'pop 85': 36,
 'pop 90': 37,
 'pop 96': 38,
 'rock 14': 39,
 'rock 15': 40,
 'rock 22': 41,
 'rock 24': 42,
 'rock 31': 43,
 'rock 34': 44,
 'rock 35': 45,
 'rock 4': 46,
 'rock 50': 47,
 'rock 57': 48,
 'rock 84': 49,
 'rock 89': 50,
 'rock 92': 51}

In [33]:
t = torch.arange(5)
t[1] = 4
t

tensor([0, 4, 2, 3, 4])

In [43]:
(torch.arange(16) // 5).view(4, 4).mode(1)

torch.return_types.mode(
values=tensor([0, 1, 1, 2]),
indices=tensor([3, 3, 1, 2]))

In [49]:
torch.arange(16).view(8, 2).mode(1).values

tensor([ 0,  2,  4,  6,  8, 10, 12, 14])

In [34]:
t.mode().values

tensor(4)

In [45]:
73728 / 768

96.0

# meta

In [ ]:
'filename_h5'
'filename_music_meta'
'shape'

In [28]:
import h5py
import pandas as pd

t = '/Users/ksc/Desktop/Нейротемка/music_data/h5/'

res = []

for i in range(1, 8):
    res.append({})
    res[-1]['filename_h5'] = f'session_eeg_{i}.h5'
    res[-1]['filename_music_meta'] = f'events_{i}.csv'
    with h5py.File(f'/Users/ksc/Desktop/Нейротемка/music_data/h5/session_eeg_{i}.h5', "r") as f:
        res[-1]['shape'] = f['eeg4_datasetName']['eeg2_name'].shape[0]
        res[-1]['start_timestamp'] = f['eeg4_datasetName'].attrs['eeg4_datasetAttributeStartTime'] / (10 ** 6)
mt = pd.DataFrame(res)
mt

filename_h5 filename_music_meta   shape  start_timestamp
0  session_eeg_1.h5        events_1.csv  690304     1.711531e+09
1  session_eeg_2.h5        events_2.csv  437632     1.711543e+09
2  session_eeg_3.h5        events_3.csv  486304     1.711537e+09
3  session_eeg_4.h5        events_4.csv  800256     1.711539e+09
4  session_eeg_5.h5        events_5.csv  469152     1.711549e+09
5  session_eeg_6.h5        events_6.csv  468544     1.711535e+09
6  session_eeg_7.h5        events_7.csv  382400     1.711545e+09

In [29]:
mt.to_parquet('/Users/ksc/Desktop/Нейротемка/music_data/h5/metadata.parquet', index=False)

In [17]:
import h5py

with h5py.File('/Users/ksc/Desktop/Нейротемка/music_data/h5/session_eeg_1.h5', "r") as f:
    print(dict(f['eeg4_datasetName'].attrs.items())['eeg4_datasetAttributeStartTime'])
    print(f['eeg4_datasetName'].attrs['eeg4_datasetAttributeStartTime'])
    f['eeg4_datasetName']['eeg2_name'].shape[0]

1711530719213214
1711530719213214


# check dataset

In [1]:
import os
os.chdir(os.path.join(os.getcwd(), '..'))

In [2]:
from dataset.labeled_dataset import EEGLabeledDataset

dataset = EEGLabeledDataset(
    data_path='/Users/ksc/Desktop/Нейротемка/music_data/h5',
    cache_processed_path='/Users/ksc/Desktop/Нейротемка/music_data/cache',
    train_length=73728,
    dataset_mode='sequential',
    target_config={
        'user_id': True,
        'activity': True
    },
    clipped_threshold=100
)

Building cache...


One chunk from each file:  29%|██▊       | 2/7 [00:00<00:01,  4.44it/s]

Skipping last 25752
Skipping last 67992


One chunk from each file:  43%|████▎     | 3/7 [00:00<00:00,  4.70it/s]

Skipping last 42936


One chunk from each file:  57%|█████▋    | 4/7 [00:00<00:00,  3.97it/s]

Skipping last 61976
Skipping last 25784


One chunk from each file: 100%|██████████| 7/7 [00:01<00:00,  4.53it/s]

Skipping last 25176
Skipping last 12760


In [3]:
((dataset[6]['is_liked'] == 2) * 1.0).mean()

tensor(0.5156)

In [4]:
for i in range(len(dataset)):
    print(dataset[i]['user_id'])

tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(0)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(1)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(2)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(3)
tensor(4)
tensor(4)
tensor(4)
tensor(4)
tensor(4)
tensor(4)
tensor(5)
tensor(5)
tensor(5)
tensor(5)
tensor(5)
tensor(5)
tensor(6)
tensor(6)
tensor(6)
tensor(6)
tensor(6)


In [10]:
dataset[8]['song_ids']

tensor([42, 42, 42,  0,  0,  0,  0,  0,  0,  0,  0,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  0,  0,
         0,  0,  0,  0,  0,  0, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
        40, 40, 40, 40, 40, 40, 40, 40, 

In [27]:
dataset.metadata

filename_h5 filename_music_meta   shape  start_timestamp  user_id
0  session_eeg_1.h5        events_1.csv  690304     1.711531e+09        0
1  session_eeg_2.h5        events_2.csv  437632     1.711543e+09        1
2  session_eeg_3.h5        events_3.csv  486304     1.711537e+09        2
3  session_eeg_4.h5        events_4.csv  800256     1.711539e+09        3
4  session_eeg_5.h5        events_5.csv  469152     1.711549e+09        4
5  session_eeg_6.h5        events_6.csv  468544     1.711535e+09        5

In [14]:
len(dataset)

42